In [1]:
# Tensors are a specialized data structure that are very similar to arrays and matrices.
# In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

# pip install torch

In [2]:
import torch
import numpy as np

In [13]:
data = [[1,2,3,4], [5,6,7,8]]
x_data = torch.tensor(data)
print(x_data)

np_array = np.array(data)
x_numpy = torch.from_numpy(np_array)
print(np_array)
print(x_numpy)

# Change in Numpy array reflects in tensor & vice versa
# They share the same underlying memeory, no need to copy
# Does not happen with plain data array. Happens with numpy array only
np.add(np_array, 1, out=np_array)
print(np_array)
print(x_numpy)


x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

x_f_data = torch.tensor([[1.0,2.0], [5.0,6.0]])
x_f_rand = torch.rand_like(x_f_data)
print(x_f_rand)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
[[1 2 3 4]
 [5 6 7 8]]
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
[[2 3 4 5]
 [6 7 8 9]]
tensor([[2, 3, 4, 5],
        [6, 7, 8, 9]])
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])
tensor([[0.8048, 0.4000, 0.6323, 0.0427],
        [0.5106, 0.2316, 0.4490, 0.2167]])
tensor([[0.8530, 0.3673],
        [0.1197, 0.5457]])


In [14]:
shape = (4,5,)

rand_t = torch.rand(shape)
print(rand_t)

ones_t = torch.ones(shape)
print(ones_t)

zeros_t = torch.zeros(shape)
print(zeros_t)

tensor([[0.6620, 0.6053, 0.4675, 0.3079, 0.6827],
        [0.9384, 0.7994, 0.7651, 0.2248, 0.2510],
        [0.0493, 0.9045, 0.8399, 0.3936, 0.5716],
        [0.3584, 0.9453, 0.4049, 0.9550, 0.9871]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [15]:
tensor = torch.rand(4,5)
print(tensor)

print(f'The shape of tensor is {tensor.shape}')
print(f'The datatype of tensor is {tensor.dtype}')
print(f'The device of the tensor is {tensor.device}')

tensor([[0.9737, 0.2332, 0.8897, 0.9535, 0.1822],
        [0.3364, 0.2354, 0.8880, 0.9725, 0.4464],
        [0.1354, 0.1605, 0.3951, 0.1101, 0.9077],
        [0.1778, 0.0968, 0.6057, 0.0040, 0.8721]])
The shape of tensor is torch.Size([4, 5])
The datatype of tensor is torch.float32
The device of the tensor is cpu


In [16]:
print(torch.cuda.is_available())

False


In [17]:
print(f'First row: {tensor[0]}')
print(f'First column: {tensor[:, 0]}')
print(f'Last column: {tensor[..., -1]}')

First row: tensor([0.9737, 0.2332, 0.8897, 0.9535, 0.1822])
First column: tensor([0.9737, 0.3364, 0.1354, 0.1778])
Last column: tensor([0.1822, 0.4464, 0.9077, 0.8721])


In [18]:
t1 = torch.ones([2,3])
t2 = torch.zeros([2,3])
print(f't1: {t1}')
print(f't2: {t2}')
t3 = torch.cat([t1,t2])
t4 = torch.cat([t3, t1])
print(f't3: {t3}')
print(f't4: {t4}')

t1: tensor([[1., 1., 1.],
        [1., 1., 1.]])
t2: tensor([[0., 0., 0.],
        [0., 0., 0.]])
t3: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])
t4: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [19]:
t1 = torch.ones(3,3)
t1[:, 1] = 0
t1t = t1.T
print(t1)
print(t1t)

tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])
tensor([[1., 1., 1.],
        [0., 0., 0.],
        [1., 1., 1.]])


In [20]:
t1 = torch.ones(2,3)
t2 = torch.rand(3,2)
t1t2 = t1.matmul(t2) 
print(t1)
print(t2)
print(t1t2)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.6421, 0.3839],
        [0.9227, 0.0641],
        [0.8191, 0.0937]])
tensor([[2.3839, 0.5417],
        [2.3839, 0.5417]])


In [21]:
t1 = torch.rand(3,2)
print(t1)
t1.add_(1)
print(t1)

tensor([[0.8232, 0.3635],
        [0.9252, 0.5897],
        [0.7833, 0.5167]])
tensor([[1.8232, 1.3635],
        [1.9252, 1.5897],
        [1.7833, 1.5167]])
