In [4]:
import torch
import numpy as np

In [5]:
# Demonstrate autograd

x = torch.rand(3,2, requires_grad=True)
print(x)

y = x + 1
print(y)

# can't do below as implicit grad is for scalar inputs only
# for non scalar inputs we need to provide a vector explicitly in the argument
# y.backward()

z = y.mean()
print(z)

z.backward()
print(x.grad)

# can't do below as .grad attribute is for leaf tensors only
# print(y.grad)

tensor([[0.9203, 0.2196],
        [0.0322, 0.6973],
        [0.4976, 0.1646]], requires_grad=True)
tensor([[1.9203, 1.2196],
        [1.0322, 1.6973],
        [1.4976, 1.1646]], grad_fn=<AddBackward0>)
tensor(1.4219, grad_fn=<MeanBackward0>)
tensor([[0.1667, 0.1667],
        [0.1667, 0.1667],
        [0.1667, 0.1667]])


In [6]:
# Demonstrate backpropagation with autograd

a = torch.ones(1,1)
w = torch.ones(1,1, requires_grad=True)

# Forward pass and loss calculation
b = a * w
b_validate = a+1 # Value to validate b against
loss = (b-b_validate) ** 2
loss.backward()
print(w.grad)
# Gradient should be -2 based on the rules of gradient chaining for local gradients
# dloss/dw = dloss/db * db/dw

tensor([[-2.]])
